spring:
  application:
    name: currency-conversion-service

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8100

eureka:
  instance:
    prefer-ip-address: true
    #hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka