spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/Haidranoid/IdeaProjects/spring-boot-microservices-v2/git-local-config-repository

server:
  port: 8888
